version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    environment:
      - NODE_ENV=production
      - DARWIN_PUSH_PORT_USERNAME=${DARWIN_PUSH_PORT_USERNAME}
      - DARWIN_PUSH_PORT_PASSWORD=${DARWIN_PUSH_PORT_PASSWORD}
      - DARWIN_MESSAGING_HOST=${DARWIN_MESSAGING_HOST}
      - DARWIN_STOMP_PORT=${DARWIN_STOMP_PORT}
      - DARWIN_OPENWIRE_PORT=${DARWIN_OPENWIRE_PORT}
      - DARWIN_TOPIC_LIVE=${DARWIN_TOPIC_LIVE}
      - DARWIN_TOPIC_STATUS=${DARWIN_TOPIC_STATUS}
      - FRONTEND_URL=${FRONTEND_URL:-http://frontend:3000}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  backend_data:
  frontend_data:

